#!/usr/bin/python3
import sys,os

statics = {
    "Google":"8.8.8.8",
    "Fransa1":"80.118.196.36",
    "Fransa2":"80.118.196.42",
    "Fransa3":"84.103.237.143",
    "Fransa4":"67.215.9.250",
    "Kanada1":"192.26.210.1",
    "Kanada2":"206.191.0.139",
    "Kanada3":"66.209.48.10",
    "İtalya1":"85.38.28.73",
    "İtalya2":"85.38.28.90",
    "İtalya3":"93.185.112.2",
    "İtalya4":"85.38.28.72",
    "United_States1":"64.81.79.2",
    "United_States2":"128.107.241.184",
    "United_States3":"207.126.96.162",
    "Youtube_Twitter_1":"8.26.56.26",
    "Youtube_Twitter_2":"77.88.8.8",
    "Youtube_Twitter_3":"195.46.39.39",
    "Youtube_Twitter_4":"151.203.0.85"
}


def configure_write(dns = None):
    configure_file = open("/etc/resolv.conf","w")
    if dns == None:
        print("\033[91mDNS belirtilmedi!\033[0m")
        sys.exit()
    else:
        data = """
# Generated by NetworkManager
nameserver {}
        """.format(dns)
        configure_file.write(data)
    configure_file.close()
    os.system("/etc/init.d/networking restart")


def usage():
    print("""\033[93m
    Creator by: Volkan Taşcı

    Manuel:
        dns_changer.py nameserver
    Static:
        dns_changer.py static_dns_name

    Show Static DNS servers:
        dns_changer.py show_statics

    Example Static:
        dns_changer.py Google

    Example Manuel:
        dns_changer.py 8.8.8.8
    \033[0m""")



if len(sys.argv) == 1:
    usage()
    sys.exit()
elif len(sys.argv) == 2:
    if sys.argv[1] == "show_statics":
        values = []
        keys = []
        for i in statics.keys():
            keys.append(i)

        for i in statics.values():
            values.append(i)
        sayi = len(keys)
        keys.sort()
        for i in range(sayi):
            print("\033[93m{} : \033[94m{}\033[0m".format(keys[i],statics[keys[i]]))

    if sys.argv[1] in statics.keys():
        configure_write(statics[sys.argv[1]])
        print("\033[93mDns Server Başarı İle Değiştirildi!\033[0m")
    elif sys.argv[1] != "show_statics":
        dns = sys.argv[1]
        dns = dns.split(".")
        if len(dns) == 4:
            try:
                for i in dns:
                    i = int(i)
            except ValueError:
                print("\033[91mGeçersiz Dns Server!\033[0m")
                sys.exit()
            configure_write(sys.argv[1])
            print("\033[93mDns Server Başarı İle Değiştirildi!\033[0m")
        else:
            print("\033[91mGeçersiz Dns Server!\033[0m")
